### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by justMuriithi** [aakashhdesai/climate-mood#4]
- Superb job on the visual feedback from automated sentiments analysis. In trying to replicate the same, I encounter the below error on heroku. Any ideas what I may doing wrong and how I may go about resolving it?
<img width="1207" alt="Screenshot 2019-10-14 at 17 29 48" src="https://user-images.githubusercontent.com/44572764/66759870-b41a0a80-eea9-11e9-92e6-8ae0f12d27f1.png">

**Comment by aakashhdesai** [comment]
Thanks for the compliment - part of getting the app to load is to run the climate_tweets script into a db on Heroku before deploying it (I used PostgreSQL). The dashboard won't load without a database to parse from based on its current incarnation.

I'll update the readme with a good set of instructions.

**Comment by aakashhdesai** [comment]
I've updated the README.md. Hope this helps!

**Comment by justMuriithi** [comment]
Fantastic @aakashhdesai I'm now up and running. Thank you
